/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.prog2.tooling;

public class App {
    public String getGreeting() {
        return "Hello World! Prog2";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
