/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.prog2.application;

import javafx.application.Application;

public class App {
    public static void main(String[] args) {
		Application.launch(MainWindow.class, args);
    }
}
