/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.prog2.example.code;

import ch.zhaw.prog2.example.fxml.MainWindowFXML;
import javafx.application.Application;

public class App {
    public static void main(String[] args) {
		Application.launch(MainWindowCodePublic.class, args);
    }
}
