/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.prog2.concurrency1.unimportant;

import javafx.application.Application;

public class Main {
    public static void main(String[] args) {
		Application.launch(BallBouncerDemo.class, args);
    }
}
